### ISSUE TITLE
[suggestion] CSS generating with real font-family using otfinfo

### ISSUE THREAD

**Issue by ghost** [bdusell/webfont-generator#16]
I've been <a href="https://github.com/eladkarako/1st_font_webkit_gen/blob/master/webkit-generator.cmd">playing with a CSS generator</a> for my Windows based webkit-generator, that uses <code>otfinfo --quiet --family filename.ttf</code> (it first generates one if the input file is not a ttf one), so it won't relay on whatever the filename is, but for the "font-family" entry stored in the file itself.

mine uses <code>otfinfo</code> from Cygwin with a Windows batch file,
it does not generate the font-weight or the style, although it is too, possible,
(but I think <a href="http://icompile.eladkarako.com/font-family-name/">fc-scan</a> might be better for this).

here is a CSS auto-generated from the <code>NotoEmoji-Regular.ttf</code> file:

```css
@font-face{
 font-weight:400; font-style:normal; font-display:swap; font-family:'Noto Emoji';
 src: url('NotoEmoji-Regular.eot');
 src: local('Noto Emoji')
     ,local('NotoEmoji-Regular.ttf')
     ,url('NotoEmoji-Regular.eot?#iefix')  format('embedded-opentype')
     ,url('NotoEmoji-Regular.otf')         format('opentype')
     ,url('NotoEmoji-Regular.ttf')         format('truetype')
     ,url('NotoEmoji-Regular.woff2')       format('woff2')
     ,url('NotoEmoji-Regular.woff')        format('woff')
     ,url('NotoEmoji-Regular.svg#svg')     format('svg')
     ;
}

html, input, textarea{  /*for example...*/
  font-family: 'Noto Emoji', sans-serif;
}
```

I think it will be great in your generator since it is *nix-native,
so you won't need to do all the weird pipe-things I use to grab the output :]
(and the file-name can always be used as a fallback for any reason)
